# Generated by Django 4.0.4 on 2022-04-26 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('net_worth_main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('user', 'name')},
        ),
    ]
